set_property SRC_FILE_INFO {cfile:{C:/Users/luisk/OneDrive/Documentos/2024-II/Circuitos digitales/Laboratorio_1/Practica_Reto/Practica_Reto.srcs/constrs_1/new/const_xnor.xdc} rfile:../../../Practica_Reto.srcs/constrs_1/new/const_xnor.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports A]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports B]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports C]
